import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { fetchBranding } from "@/lib/branding";
import { parseTenantFromHost } from "@/lib/tenant";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const h = await headers();
  // Prefer the tenant resolved by middleware (forwarded on the request via
  // `x-tenant`); fall back to parsing `host` directly so this still works
  // when middleware didn't run (e.g. unit tests, static rendering contexts).
  const tenant = h.get("x-tenant") ?? parseTenantFromHost(h.get("host"));
  const branding = await fetchBranding(tenant);

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {branding.primaryColor && (
          // `!important` guarantees the tenant brand color applies in BOTH
          // light and dark mode: `.dark { --color-primary: ... }` in
          // tokens.css has equal specificity to this injected `:root` rule,
          // so without `!important` a dark-mode session could fall back to
          // the default blue instead of the tenant's color. The dark-mode
          // default only takes effect when no tenant override exists.
          <style>{`:root{--color-primary:${branding.primaryColor} !important}`}</style>
        )}
      </head>
      <body className="min-h-full flex flex-col bg-bg text-ink">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
